CREATE TABLE analysis_case
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id    BIGINT,
    type          VARCHAR(255),
    status        VARCHAR(255),
    raw_file_path VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    processed_at  TIMESTAMP WITHOUT TIME ZONE,
    source        VARCHAR(255),
    CONSTRAINT pk_analysiscase PRIMARY KEY (id)
);