CREATE TABLE analysis_result
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    analysis_case_id BIGINT,
    summary          VARCHAR(255),
    findings         VARCHAR(255),
    risk_level       VARCHAR(255),
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_analysisresult PRIMARY KEY (id)
);